Fixed Build Error

diff --git a/.github/workflows/master_dev_ci.yml b/.github/workflows/master_dev_ci.yml
--- a/.github/workflows/master_dev_ci.yml
+++ b/.github/workflows/master_dev_ci.yml
@@ -180,22 +180,22 @@ jobs:
         continue-on-error: true
         run: ./gradlew :androidApp:checkReleaseBadging
 
-      - name: Prevent updating Dependency Guard baselines if this is a fork
+      - name: Prevent updating release badging if this is a fork
         id: checkfork_badging
         if: steps.badging_verify.outcome == 'failure' && github.event.pull_request.head.repo.full_name != github.repository
         run: |
-          echo "::error::Dependency Guard failed, please update badging with: ./gradlew updateReleaseBadging" && exit 1
+          echo "::error::Release Badging failed, please update badging with: ./gradlew updateReleaseBadging" && exit 1
 
 
         # Runs if previous job failed
-      - name: Generate new Dependency Guard baselines if verification failed and it's a PR
+      - name: Generate new release badging if verification failed and it's a PR
         id: generate_badging
         if: steps.checkfork_badging.outcome == 'failure' && github.event_name == 'pull_request'
         run: |
           ./gradlew updateReleaseBadging
 
 
-      - name: Push new Dependency Guard baselines if available
+      - name: Push new release badging if available
         uses: stefanzweifel/git-auto-commit-action@v5
         if: steps.generate_badging.outcome == 'success'
         with:
